
-- ==========================================
-- This script populates the metadata tables with entries for dimensions and fact tables.
-- This is meant to be run after init_core_metadata.sql, which creates the tables and roles
-- ==========================================

INSERT INTO core.metadata (
    modelname,
    sourcetablename,
    stagingtablename,
    table_type,
    description,
    active
)
VALUES
('dim1', 'raw_dim1', 'stage_dim1', 'dimensions', 'Dim1 dimension table', true),
('dim2', 'raw_dim2', 'stage_dim2', 'dimensions', 'dim2 dimension table', true),
('dim3', 'raw_dim3', 'stage_dim3', 'dimensions', 'dim3 dimension table', true),
('dim4', 'raw_dim4', 'stage_dim4', 'dimensions', 'dim4 dimension table', true),
('dim5', 'raw_dim5', 'stage_dim5', 'dimensions', 'dim5 dimension table', true),
('dim6', 'raw_dim6', 'stage_dim6', 'dimensions', 'dim6 dimension table', true),
('dim7', 'raw_dim7', 'stage_dim7', 'dimensions', 'dim7 dimension table', true),
('dim8', 'raw_dim8', 'stage_dim8', 'dimensions', 'dim8 dimension table', true),
('dim9', 'raw_dim9', 'stage_dim9', 'dimensions', 'dim9 dimension table', true),
('fact_transactions', 'raw_transactions', 'stage_transactions', 'fact', 'Fact Table for Transactions', true);

-- ==========================================
-- This script populates the metadata_columns tables with entries for dimensions and fact tables.
-- This is meant to be run after init_core_metadata.sql, which creates the tables and roles
-- ==========================================

INSERT INTO core.metadata_columns(sourcetablename,column_name,table_type,column_type,description, is_primary_key,is_unique,is_nullable) 
VALUES
('dim1','label','marts','varchar(100)','Human-readable label',FALSE,FALSE,FALSE),
('dim1','is_active','marts','boolean','Indicates whether the record is active',FALSE,FALSE,FALSE),
('dim1','effective_from','marts','timestamp','Start of effective date range',FALSE,FALSE,FALSE),
('dim1','ingestion_timestamp','marts','timestamp','Timestamp when record was ingested',FALSE,FALSE,FALSE),
('dim1','effective_to','marts','timestamp','End of effective date range',FALSE,FALSE,TRUE),
('dim1','dim1_sk','marts','text','Surrogate key for dim1',TRUE,TRUE,FALSE),
('dim1','code','marts','varchar(50)','Dimension code',FALSE,FALSE,FALSE),
('dim2','code','marts','varchar(50)','Dimension code',FALSE,FALSE,FALSE),
('dim2','label','marts','varchar(100)','Human-readable label',FALSE,FALSE,FALSE),
('dim2','is_active','marts','boolean','Indicates whether the record is active',FALSE,FALSE,FALSE),
('dim2','effective_from','marts','timestamp','Start of effective date range',FALSE,FALSE,FALSE),
('dim2','ingestion_timestamp','marts','timestamp','Timestamp when record was ingested',FALSE,FALSE,FALSE),
('dim2','dim2_sk','marts','text','Surrogate key for dim1',TRUE,TRUE,FALSE),
('dim2','effective_to','marts','timestamp','End of effective date range',FALSE,FALSE,TRUE),
('dim3','code','marts','varchar(50)','Dimension code',FALSE,FALSE,FALSE),
('dim3','label','marts','varchar(100)','Human-readable label',FALSE,FALSE,FALSE),
('dim3','is_active','marts','boolean','Indicates whether the record is active',FALSE,FALSE,FALSE),
('dim3','effective_from','marts','timestamp','Start of effective date range',FALSE,FALSE,FALSE),
('dim3','ingestion_timestamp','marts','timestamp','Timestamp when record was ingested',FALSE,FALSE,FALSE),
('dim3','dim3_sk','marts','text','Surrogate key for dim1',TRUE,TRUE,FALSE),
('dim3','effective_to','marts','timestamp','End of effective date range',FALSE,FALSE,TRUE),
('dim4','code','marts','varchar(50)','Dimension code',FALSE,FALSE,FALSE),
('dim4','label','marts','varchar(100)','Human-readable label',FALSE,FALSE,FALSE),
('dim4','is_active','marts','boolean','Indicates whether the record is active',FALSE,FALSE,FALSE),
('dim4','effective_from','marts','timestamp','Start of effective date range',FALSE,FALSE,FALSE),
('dim4','ingestion_timestamp','marts','timestamp','Timestamp when record was ingested',FALSE,FALSE,FALSE),
('dim4','dim4_sk','marts','text','Surrogate key for dim1',TRUE,TRUE,FALSE),
('dim4','effective_to','marts','timestamp','End of effective date range',FALSE,FALSE,TRUE),
('dim5','code','marts','varchar(50)','Dimension code',FALSE,FALSE,FALSE),
('dim5','label','marts','varchar(100)','Human-readable label',FALSE,FALSE,FALSE),
('dim5','is_active','marts','boolean','Indicates whether the record is active',FALSE,FALSE,FALSE),
('dim5','effective_from','marts','timestamp','Start of effective date range',FALSE,FALSE,FALSE),
('dim5','ingestion_timestamp','marts','timestamp','Timestamp when record was ingested',FALSE,FALSE,FALSE),
('dim5','dim5_sk','marts','text','Surrogate key for dim1',TRUE,TRUE,FALSE),
('dim5','effective_to','marts','timestamp','End of effective date range',FALSE,FALSE,TRUE),
('dim6','code','marts','varchar(50)','Dimension code',FALSE,FALSE,FALSE),
('dim6','label','marts','varchar(100)','Human-readable label',FALSE,FALSE,FALSE),
('dim6','is_active','marts','boolean','Indicates whether the record is active',FALSE,FALSE,FALSE),
('dim6','effective_from','marts','timestamp','Start of effective date range',FALSE,FALSE,FALSE),
('dim6','ingestion_timestamp','marts','timestamp','Timestamp when record was ingested',FALSE,FALSE,FALSE),
('dim6','dim6_sk','marts','text','Surrogate key for dim1',TRUE,TRUE,FALSE),
('dim6','effective_to','marts','timestamp','End of effective date range',FALSE,FALSE,TRUE),
('dim7','code','marts','varchar(50)','Dimension code',FALSE,FALSE,FALSE),
('dim7','label','marts','varchar(100)','Human-readable label',FALSE,FALSE,FALSE),
('dim7','is_active','marts','boolean','Indicates whether the record is active',FALSE,FALSE,FALSE),
('dim7','effective_from','marts','timestamp','Start of effective date range',FALSE,FALSE,FALSE),
('dim7','ingestion_timestamp','marts','timestamp','Timestamp when record was ingested',FALSE,FALSE,FALSE),
('dim7','dim7_sk','marts','text','Surrogate key for dim1',TRUE,TRUE,FALSE),
('dim7','effective_to','marts','timestamp','End of effective date range',FALSE,FALSE,TRUE),
('dim8','code','marts','varchar(50)','Dimension code',FALSE,FALSE,FALSE),
('dim8','label','marts','varchar(100)','Human-readable label',FALSE,FALSE,FALSE),
('dim8','dim8_sk','marts','text','Surrogate key for dim1',TRUE,TRUE,FALSE),
('dim8','is_active','marts','boolean','Indicates whether the record is active',FALSE,FALSE,FALSE),
('dim8','effective_from','marts','timestamp','Start of effective date range',FALSE,FALSE,FALSE),
('dim8','ingestion_timestamp','marts','timestamp','Timestamp when record was ingested',FALSE,FALSE,FALSE),
('dim8','effective_to','marts','timestamp','End of effective date range',FALSE,FALSE,TRUE),
('dim9','code','marts','varchar(50)','Dimension code',FALSE,FALSE,FALSE),
('dim9','label','marts','varchar(100)','Human-readable label',FALSE,FALSE,FALSE),
('dim9','is_active','marts','boolean','Indicates whether the record is active',FALSE,FALSE,FALSE),
('dim9','effective_from','marts','timestamp','Start of effective date range',FALSE,FALSE,FALSE),
('dim9','ingestion_timestamp','marts','timestamp','Timestamp when record was ingested',FALSE,FALSE,FALSE),
('dim9','effective_to','marts','timestamp','End of effective date range',FALSE,FALSE,TRUE),
('dim9','dim9_sk','marts','text','Surrogate key for dim1',TRUE,TRUE,FALSE),
('fact_transactions','measure1','marts','numeric','Fact measure 1',FALSE,FALSE,FALSE),
('fact_transactions','measure2','marts','numeric','Fact measure 2',FALSE,FALSE,FALSE),
('fact_transactions','measure3','marts','numeric','Fact measure 3',FALSE,FALSE,FALSE),
('fact_transactions','measure4','marts','numeric','Fact measure 4',FALSE,FALSE,FALSE),
('fact_transactions','measure5','marts','numeric','Fact measure 5',FALSE,FALSE,FALSE),
('fact_transactions','source_system','marts','varchar(50)','Source system identifier',FALSE,FALSE,FALSE),
('fact_transactions','ingestion_timestamp','marts','timestamp','Timestamp when record was ingested',FALSE,FALSE,FALSE),
('fact_transactions','fact_transactions_sk','marts','text','Surrogate key for fact_transactions',TRUE,TRUE,FALSE),
('fact_transactions','dim2_sk','marts','text','Foreign key to dim2',FALSE,FALSE,FALSE),
('fact_transactions','dim3_sk','marts','text','Foreign key to dim3',FALSE,FALSE,FALSE),
('fact_transactions','dim4_sk','marts','text','Foreign key to dim4',FALSE,FALSE,FALSE),
('fact_transactions','dim5_sk','marts','text','Foreign key to dim5',FALSE,FALSE,FALSE),
('fact_transactions','dim6_sk','marts','text','Foreign key to dim6',FALSE,FALSE,FALSE),
('fact_transactions','dim7_sk','marts','text','Foreign key to dim7',FALSE,FALSE,FALSE),
('fact_transactions','dim8_sk','marts','text','Foreign key to dim8',FALSE,FALSE,FALSE),
('fact_transactions','dim9_sk','marts','text','Foreign key to dim9',FALSE,FALSE,FALSE),
('fact_transactions','dim1_sk','marts','text','Foreign key to dim1',FALSE,FALSE,FALSE),
('raw_dim1','dim1_code','raw','varchar(50)','A generic code description for dim1_code',TRUE,TRUE,FALSE),
('raw_dim1','dim1_label','raw','varchar(100)','A generic label description for dim1_label',FALSE,FALSE,FALSE),
('raw_dim1','sort_order','raw','int','Sort order of the record',FALSE,FALSE,FALSE),
('raw_dim1','is_active','raw','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('raw_dim1','source_system','raw','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('raw_dim1','ingestion_timestamp','raw','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('raw_dim2','dim2_code','raw','varchar(50)','A generic code description for dim2_code',TRUE,TRUE,FALSE),
('raw_dim2','dim2_label','raw','varchar(100)','A generic label description for dim2_label',FALSE,FALSE,FALSE),
('raw_dim2','sort_order','raw','int','Sort order of the record',FALSE,FALSE,FALSE),
('raw_dim2','is_active','raw','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('raw_dim2','source_system','raw','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('raw_dim2','ingestion_timestamp','raw','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('raw_dim3','dim3_code','raw','varchar(50)','A generic code description for dim3_code',TRUE,TRUE,FALSE),
('raw_dim3','dim3_label','raw','varchar(100)','A generic label description for dim3_label',FALSE,FALSE,FALSE),
('raw_dim3','sort_order','raw','int','Sort order of the record',FALSE,FALSE,FALSE),
('raw_dim3','is_active','raw','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('raw_dim3','source_system','raw','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('raw_dim3','ingestion_timestamp','raw','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('raw_dim4','dim4_code','raw','varchar(50)','A generic code description for dim4_code',TRUE,TRUE,FALSE),
('raw_dim4','dim4_label','raw','varchar(100)','A generic label description for dim4_label',FALSE,FALSE,FALSE),
('raw_dim4','sort_order','raw','int','Sort order of the record',FALSE,FALSE,FALSE),
('raw_dim4','is_active','raw','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('raw_dim4','source_system','raw','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('raw_dim4','ingestion_timestamp','raw','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('raw_dim5','dim5_code','raw','varchar(50)','A generic code description for dim5_code',TRUE,TRUE,FALSE),
('raw_dim5','dim5_label','raw','varchar(100)','A generic label description for dim5_label',FALSE,FALSE,FALSE),
('raw_dim5','sort_order','raw','int','Sort order of the record',FALSE,FALSE,FALSE),
('raw_dim5','is_active','raw','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('raw_dim5','source_system','raw','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('raw_dim5','ingestion_timestamp','raw','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('raw_dim6','dim6_code','raw','varchar(50)','A generic code description for dim6_code',TRUE,TRUE,FALSE),
('raw_dim6','dim6_label','raw','varchar(100)','A generic label description for dim6_label',FALSE,FALSE,FALSE),
('raw_dim6','sort_order','raw','int','Sort order of the record',FALSE,FALSE,FALSE),
('raw_dim6','is_active','raw','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('raw_dim6','source_system','raw','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('raw_dim6','ingestion_timestamp','raw','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('raw_dim7','dim7_code','raw','varchar(50)','A generic code description for dim7_code',TRUE,TRUE,FALSE),
('raw_dim7','dim7_label','raw','varchar(100)','A generic label description for dim7_label',FALSE,FALSE,FALSE),
('raw_dim7','sort_order','raw','int','Sort order of the record',FALSE,FALSE,FALSE),
('raw_dim7','is_active','raw','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('raw_dim7','source_system','raw','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('raw_dim7','ingestion_timestamp','raw','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('raw_dim8','dim8_code','raw','varchar(50)','A generic code description for dim8_code',TRUE,TRUE,FALSE),
('raw_dim8','dim8_label','raw','varchar(100)','A generic label description for dim8_label',FALSE,FALSE,FALSE),
('raw_dim8','sort_order','raw','int','Sort order of the record',FALSE,FALSE,FALSE),
('raw_dim8','is_active','raw','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('raw_dim8','source_system','raw','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('raw_dim8','ingestion_timestamp','raw','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('raw_dim9','dim9_code','raw','varchar(50)','A generic code description for dim9_code',TRUE,TRUE,FALSE),
('raw_dim9','dim9_label','raw','varchar(100)','A generic label description for dim9_label',FALSE,FALSE,FALSE),
('raw_dim9','sort_order','raw','int','Sort order of the record',FALSE,FALSE,FALSE),
('raw_dim9','is_active','raw','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('raw_dim9','source_system','raw','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('raw_dim9','ingestion_timestamp','raw','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('stage_dim1','is_active','staging','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('stage_dim1','source_system','staging','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('stage_dim1','ingestion_timestamp','staging','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('stage_dim1','code','staging','varchar(50)','A generic code description for dim1_code',TRUE,TRUE,FALSE),
('stage_dim1','label','staging','varchar(100)','A generic label description for dim1_label',FALSE,FALSE,FALSE),
('stage_dim1','sort_order','staging','int','Sort order of the record',FALSE,FALSE,FALSE),
('stage_dim2','is_active','staging','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('stage_dim2','source_system','staging','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('stage_dim2','ingestion_timestamp','staging','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('stage_dim2','code','staging','varchar(50)','A generic code description for dim2_code',TRUE,TRUE,FALSE),
('stage_dim2','label','staging','varchar(100)','A generic label description for dim2_label',FALSE,FALSE,FALSE),
('stage_dim2','sort_order','staging','int','Sort order of the record',FALSE,FALSE,FALSE),
('stage_dim3','is_active','staging','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('stage_dim3','source_system','staging','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('stage_dim3','ingestion_timestamp','staging','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('stage_dim3','code','staging','varchar(50)','A generic code description for dim3_code',TRUE,TRUE,FALSE),
('stage_dim3','label','staging','varchar(100)','A generic label description for dim3_label',FALSE,FALSE,FALSE),
('stage_dim3','sort_order','staging','int','Sort order of the record',FALSE,FALSE,FALSE),
('stage_dim4','is_active','staging','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('stage_dim4','source_system','staging','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('stage_dim4','ingestion_timestamp','staging','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('stage_dim4','code','staging','varchar(50)','A generic code description for dim4_code',TRUE,TRUE,FALSE),
('stage_dim4','label','staging','varchar(100)','A generic label description for dim4_label',FALSE,FALSE,FALSE),
('stage_dim4','sort_order','staging','int','Sort order of the record',FALSE,FALSE,FALSE),
('stage_dim5','is_active','staging','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('stage_dim5','source_system','staging','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('stage_dim5','ingestion_timestamp','staging','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('stage_dim5','code','staging','varchar(50)','A generic code description for dim5_code',TRUE,TRUE,FALSE),
('stage_dim5','label','staging','varchar(100)','A generic label description for dim5_label',FALSE,FALSE,FALSE),
('stage_dim5','sort_order','staging','int','Sort order of the record',FALSE,FALSE,FALSE),
('stage_dim6','is_active','staging','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('stage_dim6','source_system','staging','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('stage_dim6','ingestion_timestamp','staging','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('stage_dim6','code','staging','varchar(50)','A generic code description for dim6_code',TRUE,TRUE,FALSE),
('stage_dim6','label','staging','varchar(100)','A generic label description for dim6_label',FALSE,FALSE,FALSE),
('stage_dim6','sort_order','staging','int','Sort order of the record',FALSE,FALSE,FALSE),
('stage_dim7','is_active','staging','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('stage_dim7','source_system','staging','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('stage_dim7','ingestion_timestamp','staging','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('stage_dim7','code','staging','varchar(50)','A generic code description for dim7_code',TRUE,TRUE,FALSE),
('stage_dim7','label','staging','varchar(100)','A generic label description for dim7_label',FALSE,FALSE,FALSE),
('stage_dim7','sort_order','staging','int','Sort order of the record',FALSE,FALSE,FALSE),
('stage_dim8','sort_order','staging','int','Sort order of the record',FALSE,FALSE,FALSE),
('stage_dim8','is_active','staging','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('stage_dim8','source_system','staging','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('stage_dim8','ingestion_timestamp','staging','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('stage_dim8','code','staging','varchar(50)','A generic code description for dim8_code',TRUE,TRUE,FALSE),
('stage_dim8','label','staging','varchar(100)','A generic label description for dim8_label',FALSE,FALSE,FALSE),
('stage_dim9','sort_order','staging','int','Sort order of the record',FALSE,FALSE,FALSE),
('stage_dim9','is_active','staging','boolean','Flag indicating if record is active',FALSE,FALSE,FALSE),
('stage_dim9','source_system','staging','varchar(50)','Source system of the data',FALSE,FALSE,FALSE),
('stage_dim9','ingestion_timestamp','staging','timestamp','Timestamp when data was ingested',FALSE,FALSE,FALSE),
('stage_dim9','code','staging','varchar(50)','A generic code description for dim9_code',TRUE,TRUE,FALSE),
('stage_dim9','label','staging','varchar(100)','A generic label description for dim9_label',FALSE,FALSE,FALSE),
('stage_transactions','record_id','staging','varchar(20)','Unique record identifier',TRUE,TRUE,FALSE),
('stage_transactions','transaction_id','staging','varchar(20)','Transaction identifier',FALSE,FALSE,FALSE),
('stage_transactions','dim1_code','staging','varchar(50)','Dimension 1 code',FALSE,FALSE,FALSE),
('stage_transactions','dim2_code','staging','varchar(50)','Dimension 2 code',FALSE,FALSE,FALSE),
('stage_transactions','dim3_code','staging','varchar(50)','Dimension 3 code',FALSE,FALSE,FALSE),
('stage_transactions','dim4_code','staging','varchar(50)','Dimension 4 code',FALSE,FALSE,FALSE),
('stage_transactions','dim5_code','staging','varchar(50)','Dimension 5 code',FALSE,FALSE,FALSE),
('stage_transactions','dim6_code','staging','varchar(50)','Dimension 6 code',FALSE,FALSE,FALSE),
('stage_transactions','dim7_code','staging','varchar(50)','Dimension 7 code',FALSE,FALSE,FALSE),
('stage_transactions','dim8_code','staging','varchar(50)','Dimension 8 code',FALSE,FALSE,FALSE),
('stage_transactions','dim9_code','staging','varchar(50)','Dimension 9 code',FALSE,FALSE,FALSE),
('stage_transactions','measure1','staging','numeric','Measure 1 value',FALSE,FALSE,FALSE),
('stage_transactions','measure2','staging','numeric','Measure 2 value',FALSE,FALSE,FALSE),
('stage_transactions','measure3','staging','numeric','Measure 3 value',FALSE,FALSE,FALSE),
('stage_transactions','measure4','staging','numeric','Measure 4 value',FALSE,FALSE,FALSE),
('stage_transactions','measure5','staging','numeric','Measure 5 value',FALSE,FALSE,FALSE),
('stage_transactions','transaction_timestamp','staging','timestamp','Transaction timestamp',FALSE,FALSE,FALSE),
('stage_transactions','source_system','staging','varchar(50)','Source system identifier',FALSE,FALSE,FALSE),
('stage_transactions','ingestion_timestamp','staging','timestamp','Ingestion timestamp',FALSE,FALSE,FALSE);